# -*- coding: utf-8 -*-
"""Solución de Fernando.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vzLevqVwcCf2c-IlRslg_htWvy1eFb3a
"""

import numpy as np

#Ejercicio 2
'''Se pide escribir las instrucciones para calcular el IVA'''


#Ejercicio
def calcular_iva(totalCompra):
    resultado = totalCompra*0.19;
    print(f"El IVA de la compra es: {resultado}")

def descuento_compra(totalCompra,porc_descuento):
    descuento = totalCompra*porc_descuento;
    resultado = totalCompra - descuento
    print("------------BOLETA----------")
    print(f"TOTAL---------{totalCompra}")
    print(f"DESCUENTO---------{descuento}")
    print(f"TOTAL Dscto --------------{resultado}")

def calcular_imc(peso,altura):
    resultado = round ((peso/(altura**2)),1);
    return resultado;

def estado_imc(imc):
    if imc<18.5:
        print("ESTADO: Bajo peso")
    elif imc >= 18.5 and imc <24.9:
        print("ESTADO: Adecuado")
    elif imc >= 25. and imc <24.9:
        print("ESTADO: Sobrepeso")
    elif imc >= 30.0 and imc <24.9:
        print("ESTADO: OBESIDAD: Grado 1")
    elif imc >= 35.5 and imc <9.9:
        print("ESTADO: OBESIDAD: Grado 2")
    elif imc > 40.0:
        print("ESTADO: OBESIDAD: Grado 3")




while True:
    print("----Menú----")
    print("1.- Calcular IVA")
    print("2.- Calcular 50% Descuento")
    print("3.- Calcular 20% Descuento")
    print("4.- Calcular IMC")
    opcion = int(input("Ingrese su opcion: "))
    if opcion == 1:
        totalCompra=int(input("Ingrese valor de la compra: "))
        calcular_iva(totalCompra)
    elif opcion == 2:
        totalCompra = int(input("Ingrese valor de la compra "))
        descuento_compra(totalCompra,0.5);
    elif opcion == 3:
        totalCompra = int(input("Ingrese valor de la compra "))
        descuento_compra(totalCompra,0.2);
    elif opcion == 4:
        peso1=int(input("Ingrese su peso: "))
        altura1=float(input("Ingrese su altura: "))
        imc = calcular_imc(peso1,altura1)
        print(f"El IMC es de: {imc}")
        estado_imc(imc)